### ISSUE TITLE
Integrating Vaadin Flow to an existing Quarkus project. Can't get the routing to work without creating my own VaadinServlet

### ISSUE THREAD

**Issue by preslavrachev** [vaadin/quarkus#148] opened 2024-04-10 08:54 UTC
I am creating an administration dashboard using Vaadin, which I am going to add to my existing Quarkus app. Unfortunately, the routing does not seem to work by defaul, as the root of the application has naturally been mapped to a Quarkus route already. I noticed that the Vaadin router will try to hook itself to `/*` causing it get shadowed. 

As I only want Vaadin for that one admin use case, I discovered that I can inject a custom replacement for the `QuarkusVaadinServlet` that is mapped to `/admin/*` instead:

```java
@WebServlet(urlPatterns = "/admin/*", name = "AdminServlet", asyncSupported = true)
public class AdminServlet extends QuarkusVaadinServlet {/* ... */}
``` 

At a quick glance, this seems to work, but as it has not been documented anywhere else, I am obliged to ask. Is this the preferred way to overcome my original issue. I read somewhere that I could set a property for the mapping, but this did not work in my case.

**Comment by mcollovati** [comment] 2024-04-10 09:06
I can confirm that currently extending `QuarkusVaadinServlet` is the way to go.
Configuring mapping is supported in Spring Boot, but not on Quarkus.

I'll mark this issue as an enhancement, since configuring the mapping also in Quarkus looks a useful addition.

**Comment by preslavrachev** [comment] 2024-04-10 09:54
@mcollovati Thanks for confirming! In the meantime, shall I submit a small PR for adding this knowledge to the [documentation](https://vaadin.com/docs/latest/integrations/quarkus)? I think it will be useful for many in my situation.

**Comment by mcollovati** [comment] 2024-04-10 10:54
Contributions are more than welcome, so, please, go ahead. 

Here's the link to the docs repo https://github.com/vaadin/docs
Please make sure the PR targets `next` branch

**Comment by preslavrachev** [comment] 2024-04-17 08:46
@mcollovati PR sent, feel free to check it out and merge if you don't see any issues.

**Comment by mcollovati** [comment] 2024-05-27 07:18
Closing, as documentation has been updated in https://github.com/vaadin/docs/pull/3353 and merged.

**Closed by mcollovati** 2024-05-27 07:18 UTC
Labels: documentation, enhancement
